import { Camera } from "expo-camera";
import { SuccessToast } from "react-native-toast-message";

export default {
  // Get Started Screen
  get_started: "ابدأ الآن",
  version: "الإصدار",
  welcome_to: "مرحبًا بك في",
  primal_gym: "قوي",
  fitness_is_a_life_style: "اللياقة البدنية هي أسلوب حياة",

  // Auth Screens
  email_input_placeholder: "البريد الإلكتروني",
  password_input_placeholder: "كلمة المرور",
  remember_me: "تذكرني",
  forgot_password: "هل نسيت كلمة المرور؟",
  login_button: "تسجيل الدخول",
  email_is_not_valid: "البريد الإلكتروني غير صالح",
  email_is_required: "البريد الإلكتروني مطلوب",
  password_is_required: "كلمة المرور مطلوبة",
  password_min_length: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
  passwords_dont_match: "كلمات المرور غير متطابقة",
  male_select_option: "ذكر",
  female_select_option: "أنثى",
  gender_is_required: "الجنس مطلوب",
  name_is_required: "الاسم مطلوب",
  account_created_title: "تم إنشاء الحساب",
  account_created_message:
    "تم إنشاء الحساب بنجاح، اتصل بالإدارة لتفعيل عضويتك.",
  email_already_used: "البريد الإلكتروني مستخدم بالفعل.",
  forgot_password_title: "نسيت كلمة المرور",
  send_code_button: "إرسال الرمز",
  forgot_password_text:
    "يرجى إدخال بريدك الإلكتروني حتى نتمكن من إرسال رمز التحقق إليك.",
  back_to_login_button: "العودة لتسجيل الدخول",
  code_verification_title: "التحقق",
  code_verification: "التحقق من الرمز",
  code_verification_text:
    "لقد أرسلنا لك رمزًا للتحقق من عنوان البريد الإلكتروني",
  continue_button: "متابعة",
  reset_password_title: "إعادة تعيين كلمة المرور",
  reset_password_button: "إعادة تعيين كلمة المرور",
  new_password_input_placeholder: "كلمة مرور جديدة",
  confirm_new_password_input_placeholder: "تأكيد كلمة المرور الجديدة",
  reset_password: "إعادة تعيين كلمة المرور",
  reset_password_text: "يرجى إدخال كلمة المرور الجديدة الخاصة بك",

  // Bottom Tabs
  home_tab_title: "الرئيسية",
  calendar_tab_title: "التقويم",
  shop_tab_title: "المتاجر",
  family_tab_title: "العائلة",
  menu_tab_title: "القائمة",

  // Home Screen
  good_morning: "صباح الخير،",
  good_afternoon: "مساء الخير،",
  good_evening: "مساء الخير،",
  view_all: "عرض الكل",
  my_status_title: "حالتي",
  in_progress: "قيد التنفيذ",
  power_squad: "الفريق القوي",
  progress: "التقدم",
  calories: "السعرات الحرارية",
  weight_progress: "تقدم الوزن",
  weight: "الوزن",
  classes_title: "حصة تدريبية",
  gallery_title: "المعرض",
  off: "خصم",
  audience_title: "الجمهور",
  gym_store_title: "متجر الصالة الرياضية",

  // Shop Screen
  search_in_shop: "البحث في المتجر",
  no_products_found: "لم يتم العثور على منتجات.",
  no_stores_found: "لم يتم العثور على متاجر.",
  store_items_section_title: "منتجات المتجر",
  camera: "الكاميرا",
  gallery: "المعرض",
  cancel: "إلغاء",
  select_photo: "اختر صورة",
  camera_permission: "يجب منح إذن الكاميرا",
  // Gallery Screen
  all: "الكل",
  photos: "الصور",
  videos: "الفيديوهات",
  of: "من",
  no_items_found: "لم يتم العثور على عناصر.",

  // Latest News
  latest_news_title: "أحدث الأخبار",
  no_news_found: "لم يتم العثور على أخبار.",

  // Menu Screen
  settings: "الإعدادات",
  manage_my_account: "إدارة حسابي",
  privacy_and_safety: "الخصوصية والسلامة",
  notification: "الإشعارات",
  language: "اللغة",
  DarkMode: "الوضع الداكن",
  customers_service: "خدمة العملاء",
  logout: "تسجيل الخروج",
  payment_history: "سجل الدفع",
  my_bookings: "حجوزاتي",
  orders: "الطلبيات",
  ended: "منتهي",

  // Verify code step
  verify_code: "تأكيد الرمز",
  verify_code_text: "أدخل الرمز المرسل إلى بريدك الإلكتروني",
  code_input_placeholder: "رمز التحقق",
  verify_code_button: "تأكيد الرمز",
  code_required: "الرمز مطلوب",
  code_invalid: "يرجى إدخال رمز صحيح",

  passwords_do_not_match: "كلمتا المرور غير متطابقتين",

  // Shared
  something_went_wrong: "حدث خطأ ما، يرجى المحاولة مرة أخرى",
  // Calendar Screen
  book_now: "احجز الآن",
  event_booked_successfully: "تم حجز الفعالية بنجاح",
  event_booked: "تم حجز الفعالية",

  // Class Details Screen
  class_details_title: "تفاصيل الفصل",
  from: "من",
  to: "إلى",
  capacity: "السعة",
  members: "الأعضاء",
  persons_booked_this_class: "الأشخاص الذين حجزوا هذا الفصل",
  coach: "المدرب",
  branch: "الفرع",

  // Api Errors
  username_or_password_is_incorrect: "اسم المستخدم أو كلمة المرور غير صحيحة.",
  your_membership_expired: "انتهت صلاحية عضويتك",
  an_error_occurred: "حدث خطأ، يرجى المحاولة مرة أخرى لاحقًا.",
  session_expired: "انتهت الجلسة، يرجى تسجيل الدخول.",
  error_fetching_events: "خطأ في جلب الأحداث.",
  error_fetching_news: "خطأ في جلب الأخبار.",
  error_fetching_store_items: "خطأ في جلب عناصر المتجر.",
  error_fetching_gallery_items: "خطأ في جلب عناصر المعرض.",
  error_fetching_cart_items: "خطأ في جلب عناصر العربة.",
  error_audience: "خطأ في جلب الجمهور",

  // Product Details Screen
  buy_now: "اشترِ الآن",
  add_to_cart: "أضف إلى السلة",
  added_to_cart: "تمت إضافة المنتج إلى السلة بنجاح.",

  // Cart Screen
  cart_title: "السلة",
  cart_is_empty: "السلة فارغة",
  checkout: "الدفع",
  full_name: "الاسم الكامل",
  enter_full_name: "أدخل اسمك الكامل",
  email: "البريد الإلكتروني",
  enter_email: "أدخل بريدك الإلكتروني",
  phone: "رقم الهاتف",
  enter_phone: "أدخل رقم هاتفك",
  location: "العنوان",
  enter_location: "أدخل عنوانك",
  send: "إرسال",
  submitting: "جاري الإرسال...",
  please_fill_all_fields: "يرجى ملء جميع الحقول",
  invalid_email_format: "يرجى إدخال بريد إلكتروني صحيح",
  order_placed_successfully: "تم تقديم طلبك بنجاح!",
  ok: "حسناً",
  delete_cart_item_modal_title:
    "هل أنت متأكد أنك تريد حذف هذا العنصر من السلة؟",

  // Notifications Screen
  notifications_title: "الإشعارات",

  // Manage Account Screen
  manage_account_title: "إدارة الحساب",
  save_changes: "حفظ التغييرات",
  username_input_placeholder: "اسم المستخدم",
  username_is_required: "اسم المستخدم مطلوب",
  age_input_placeholder: "العمر",
  your_age: "عمرك",
  username_max: "يجب ألا يتجاوز اسم المستخدم 50 حرفًا",
  age_min: "الحد الأدنى للعمر هو 1",
  age_max: "الحد الأقصى للعمر هو 99",
  dob_input_placeholder: "تاريخ الميلاد",
  dob_is_required: "تاريخ الميلاد مطلوب",
  phonenumber_input_placeholder: "رقم الهاتف مطلوب",

  // My Bookings
  no_Booked_events_yet: "لا توجد فعاليات محجوزة بعد",
  my_booking_title: "حجوزاتي",
  order_date: "تاريخ الطلب",

  // Attendence and departure
  check_in_button: "تسجيل الوصول",
  requesting_permissions: "طلب إذن استخدام الكاميرا...",
  no_camera_access: "لا يوجد وصول إلى الكاميرا",
  attendance_and_departure_title: "الحضور والمغادرة",

  // Common
  empty_list_default_text: "واو، فارغة جدًا.",
  no_events_found: "لم يتم العثور على أحداث.",
  error: "خطأ",
  success: "نجاح",
  confirm: "تأكيد",
  loading: "جاري التحميل",
  save: "حفظ",
  back_to_home: "العودة إلى الصفحة الرئيسية",
  not_found: "غير موجود",
  update: "تحديث",
  nothing_to_see_here: "لا يوجد شيء هنا",
  failed_to_load: "فشل في التحميل، اضغط لإعادة المحاولة",
  welcome: "اهلا",
  MyProfile: "الملف الشخصي",
  guest_user: "زائر",

  my_profile_title: "ملفي الشخصي",

  gym_title: "النادي",
  monthly_schedule_title: "الجدول الشهري",
  reports_title: "التقارير",
  reports_overview: "نظرة عامة على التقارير",
  reports_description: "يمكنك هنا عرض وتحليل نشاطك وجداولك وملخصات الأداء.",
  monthly_report: "تقرير النشاط الشهري",
  report_placeholder:
    "لا توجد بيانات حتى الآن. سيتم إنشاء التقارير بمجرد تسجيل النشاط.",
  announcements_news_title: "الإعلانات والأخبار",
  new_equipment_title: "وصول أجهزة رياضية جديدة!",
  new_equipment_desc:
    "اطّلع على أحدث الأجهزة الرياضية المتوفّرة الآن في القاعة الرئيسية.",
  holiday_notice_title: "إشعار جدول العطلات",
  holiday_notice_desc:
    "سيتم إغلاق النادي في 20 أكتوبر لأعمال الصيانة. سيُستأنف العمل في اليوم التالي.",
  offers_title: "العروض",
  offer_1_title: "خصم 50٪ على الاشتراك السنوي",
  offer_1_desc: "اشترك في الخطة السنوية واحصل على خصم 50٪ لفترة محدودة.",
  offer_2_title: "جلسة تدريب شخصية مجانية",
  offer_2_desc:
    "اشترك في أي خطة شهرية واحصل على جلسة تدريب شخصية مجانية لمدة ساعة واحدة.",
  nutrition_plan_title: "خطة التغذية",
  nutrition_plan_basic_title: "خطة تغذية أساسية",
  nutrition_plan_basic_desc:
    "نظام غذائي متوازن للمبتدئين يركّز على الحفاظ على وزن صحي.",
  nutrition_plan_muscle_title: "خطة لزيادة الكتلة العضلية",
  nutrition_plan_muscle_desc:
    "وجبات عالية البروتين لدعم تدريب القوة ونمو العضلات.",
  nutrition_plan_weightloss_title: "خطة لخسارة الوزن",
  nutrition_plan_weightloss_desc:
    "وجبات منخفضة السعرات وغنية بالعناصر الغذائية للمساعدة في تقليل الدهون بأمان.",
  reels_title: "ريلز",
  reel_fitness_motivation: "تحفيز اللياقة",
  reel_workout_tips: "نصائح التمرين",
  reel_gym_funny: "مواقف مضحكة في النادي",
  my_progress_title: "تقدمي",
  my_progress_header: "تقدمي",
  workouts_completed: "التمارين المنجزة",
  calories_burned: "السعرات الحرارية المحروقة",
  achievements_unlocked: "الإنجازات المحققة",
  weekly_activity: "النشاط الأسبوعي",
  weekly_activity_message: "استمر في ذلك! لقد تحسنت بنسبة 18٪ هذا الأسبوع.",
  height_label: "الطول",
  weight_label: "الوزن",
  weight_target_label: "الوزن المستهدف",
  muscle_target_label: "العضلات المستهدفة",
  muscle_target_value: "الذراعان والصدر",
  number_of_workouts_label: "عدد التمارين",
  view_attendance_history: "عرض سجل الحضور الخاص بي",
  attendance_history: "سجل الحضور",
  check_in_label: "وقت الدخول",
  check_out_label: "وقت الخروج",
  status_label: "الحالة",
  no_data: "—",
  present: "حاضر",
  late: "متأخر",
  absent: "غائب",
  success_title: "تم تسجيل الحضور بنجاح",
  scanned_message: "البيانات الممسوحة:",

  scanning_in_progress_title: "جارٍ المسح",
  scanning_in_progress_message: "يرجى تثبيت الكاميرا أمام الرمز...",
  view_history: "عرض سجل الحضور",
  check_in: "تسجيل الدخول",
  check_in_success_title: "تم تسجيل الدخول بنجاح",
  check_in_success_message: "تم تسجيل حضورك بنجاح.",
  offer_details_title: "تفاصيل العرض",
  validity: "فترة الصلاحية",
  details: "التفاصيل",
  terms_conditions: "الشروط والأحكام",

  offer_1_terms:
    "العرض صالح للأعضاء الجدد فقط ولا يمكن الجمع بينه وبين عروض أخرى.",

  offer_2_terms:
    "جلسة واحدة مجانية لكل عضو ويجب حجزها خلال 30 يومًا من التسجيل.",

  gym_info_title: "معلومات النادي",

  qr_code_title: "ماسح رمز QR",
  gallery: {
    noItems: "لا توجد عناصر",
    all: "الكل",
    photos: "الصور",
    videos: "الفيديوهات",
  },
  book_class_title: "احجز صف",
  personal_trainers: "المدربين الشخصيين",
  pt_details: "تفاصيل المدرب",
  book_pt: "احجز مدرب شخصي",
  today_schedule: "جدول اليوم",
  events_on: "الفعاليات في",
  upcoming_events: "الفعاليات القادمة",
  event_time: "الوقت",
  event_description: "الوصف",
  event_title: "العنوان",
  chat: "المحادثة",
  private_chat: "دردشة خاصة",
  chat_list: "قائمة المحادثات",
  management: "الإدارة",
  member: "عضو",
  search_user: "ابحث عن مستخدم...",
  all_users: "جميع المستخدمين",

  confirm_password_placeholder: "تأكيد كلمة المرور",
  full_name_placeholder: "الاسم الكامل",

  sign_up_button: "إنشاء حساب",
  already_have_account: "هل لديك حساب؟ تسجيل الدخول",
  create_account: "إنشاء حساب",

  continue_as_guest: "الدخول كزائر",
  gallery_filters: {
    all: "الكل",
    photos: "الصور",
    videos: "الفيديوهات",
  },
  no_gallery_items: "لا توجد عناصر في المعرض",
  loading_more: "جاري التحميل...",
  error_fetching_gallery: "فشل تحميل عناصر المعرض",
  current_members: "عدد الأعضاء الحاليين",
  members_only_section: "هذا القسم متاح للأعضاء فقط",
  no_memberships_found: "لم يتم العثور على عضويات",
  learn_more: "اعرف المزيد",
  no_carousel_data: "لا توجد بيانات متاحة",
  choose_language: "اختر اللغة",
  logout_title: "تسجيل الخروج",
  logout_confirm_message: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  logout_button: "تسجيل الخروج",
  weekly_schedule: "البرنامج التدريبي الأسبوعي",
  repetitions: "عدد التكرارات",
  sets: "مجموعات",

  reps: "تكرارات",
  error_loading: "تعذر تحميل الجدول الخاص بك",
  available_classes: "🏋️ حصة تدريبية المتاحة",

  booked: "تم الحجز مسبقًا",
  booked_success: "لقد تم حجز {{class}} بنجاح!",
  already_booked: "لقد قمت بحجز هذا الفصل مسبقًا!",
  available: "متاح",
  no_class_on_date: "لا توجد حصص في هذا اليوم",

  no_products_available: "لا توجد منتجات متاحة",

  unauthorized_access: "الوصول غير مصرح به",
  an_error_occured: "حدث خطأ",
  edit_profile: "تعديل الملف الشخصي",
  gym_guest_message: "لأعضاء الصالة فقط",
  gym_traffic_title: "ازدحام الصالة",
  traffic_low: "منخفض",
  traffic_medium: "متوسط",
  traffic_high: "مرتفع",
  current_users_inside: "يوجد {{count}} مستخدمين داخل الصالة",
  attendance_success: "تم تسجيل الحضور بنجاح",
  scanned_data: "البيانات الممسوحة",

  scanning_message: "جارٍ المسح الضوئي...",

  check_out_button: "تسجيل خروج",

  checked_in_success: "تم تسجيل الدخول بنجاح",
  checked_out_success: "تم تسجيل الخروج بنجاح",

  member_id_not_found: "معرف العضو غير موجود",
  signup_button: "تسجيل",
  user: "مستخدم",
  users: "مستخدمين",
  inside: "في الداخل",
  notes: "ملاحظات",
  notifications: "الإشعارات",

  add_record: "إضافة سجل",
  edit_record: "تعديل سجل",
  record_title: "اسم السجل",
  record_value: "القيمة",
  history: "السجل السابق",

  select_color: "اختر اللون",
  upload_image: "رفع صورة",
  upload_file: "رفع ملف",
  delete_record: "حذف السجل",

  permission_required: "مطلوب إذن",
  edit: "تعديل",
  delete: "حذف",

  no_history: "لا يوجد سجل",
  close: "إغلاق",

  delete_failed: "فشل الحذف",
  AttendanceHistory: "سجل الحضور",
  no_attendance_data: "لا يوجد سجل حضور",
  no_notifications_found: "لا توجد إشعارات",
  Orders: "طلبات",
  calendar: {
    add_note: "إضافة ملاحظة",
    add_note_for: "إضافة ملاحظة بتاريخ {{date}}",
    note_placeholder: "اكتب ملاحظتك...",
    no_notes: "لا توجد ملاحظات لهذا اليوم",
    save: "حفظ",
    cancel: "إلغاء",
    note_empty_error: "لا يمكن أن تكون الملاحظة فارغة",
    note_added: "تمت إضافة الملاحظة",
    error: "خطأ",
    load_error: "تعذر تحميل الملاحظات",
    success: "تمت إضافة الملاحظة بنجاح",
    no_events: "لا توجد فعاليات مجدولة لهذا التاريخ",
  },
  profile: {
    loading: "جاري التحميل...",
    personal_info: "المعلومات الشخصية",
    physical_stats: "البيانات الجسدية",
    subscription_info: "معلومات الاشتراك",
    camera: "الكاميرا",
    gallery: "المعرض",
    cancel: "إلغاء",
    select_photo: "اختر صورة",

    full_name: "الاسم الكامل",
    arabic_name: "الاسم بالعربية",
    bio: "نبذة",
    dob: "تاريخ الميلاد",
    location: "مكان الإقامة",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    age: "العمر",
    height: "الطول",
    weight: "الوزن",
    gender: "الجنس",
    subscription_status: "حالة الاشتراك",
    expiry_date: "تاريخ الانتهاء",

    select_date: "اختر التاريخ",
    enter: "أدخل {{field}}",

    edit: "تعديل {{section}}",
    save: "حفظ التغييرات",
    delete_account: "حذف الحساب",
    delete_account_confirmation: "هل أنت متأكد من أنك تريد حذف حسابك نهائيًا؟",
    delete: "حذف",
    error: "خطأ",
    success: "تم بنجاح",
    member_not_found: "لم يتم العثور على معرف العضو.",
    delete_failed: "فشل في حذف الحساب.",
    account_deleted: "تم حذف حسابك بنجاح.",
    unable_delete_account: "تعذر حذف حسابك.",
    personal_updated: "تم تحديث المعلومات الشخصية بنجاح",

    load_error: "تعذر تحميل بيانات الملف الشخصي",
    permission_required: "إذن مطلوب",
    gallery_permission: "نحتاج إلى إذن للوصول إلى معرض الصور.",
    image_error: "فشل اختيار الصورة",
    auth_error: "رمز التحقق أو رقم العضو مفقود",
    default_name: "اسمك",

    residence_location: "مكان الإقامة",
    placeholder: "أدخل {{field}} الخاص بك",

    permission_title: "يتطلب إذنًا",
    permission_message: "يرجى السماح بالوصول إلى مكتبة الصور.",
    error_title: "خطأ",
    error_message: "تعذر تحديد الصورة.",
    updated_title: "تم تحديث الملف الشخصي",
    updated_message: "تم حفظ التغييرات بنجاح!",

    health_info: "المعلومات الصحية",
    subscription: "الاشتراك",

    // ── Physical fields ──

    male: "ذكر",
    female: "أنثى",
    target: "الهدف",
    activity_level: "مستوى النشاط",
    training_days: "أيام التدريب / الأسبوع",
    meals_per_day: "عدد الوجبات يومياً",
    notes: "ملاحظات",

    // ── Activity level options ──
    select_activity: "اختر مستوى النشاط",
    sedentary: "خامل",
    lightly_active: "نشاط خفيف",
    moderately_active: "نشاط معتدل",
    very_active: "نشاط عالٍ",

    // ── Subscription fields ──
    status: "الحالة",
    start_date: "تاريخ البدء",
  },
  my_progress: "تقدمي",
  add_progress: "+ إضافة تقدم",
  edit_progress: "تعديل التقدم",
  add_progress_modal: "إضافة تقدم",
  progress_name: "اسم التقدم",
  pick_color: "اختر اللون",
  add: "إضافة",
  value: "القيمة",
  pick_image: "اختر صورة",
  change_image: "تغيير الصورة",
  pick_file: "اختر ملف",
  change_file: "تغيير الملف",

  delete_progress_alert: "حذف التقدم؟",
  delete_history_alert: "حذف السجل؟",

  saving: "جاري الحفظ...",
  location: "الموقع",
  phone: "الهاتف",
  gym_hours: "ساعات العمل",
  no_working_hours: "لا توجد ساعات عمل متاحة",
  gym_owner: "مالك الصالة",
  location_on_map: "الموقع على الخريطة",
  open_in_maps: "افتح في الخرائط",
  map_not_available: "الموقع على الخريطة غير متاح",
  no_gym_data_found: "لا توجد بيانات للصالة الرياضية",
  request_camera_permission: "جاري طلب إذن الكاميرا...",
  camera_permission_denied: "تم رفض إذن الكاميرا. يرجى تمكينه من الإعدادات.",
  scan_qr_code: "مسح رمز الاستجابة السريعة",
  scan_again: "أعد المسح",
  scan_another_qr: "مسح رمز استجابة آخر",
  qr_code_info_not_found: "لم يتم العثور على معلومات رمز الاستجابة السريعة.",
  something_went_wrong: "حدث خطأ ما",
  class_information: "معلومات الحصة",
  attendees: "حاضرين",

  not_booked: "لم يتم الحجز",
  default_class_description:
    "انضم إلى هذه الحصة الرائعة لتحسين مرونتك وتوازنك وقوتك في بيئة محفزة.",
  book_this_class: "احجز هذه الحصة",
  cancel_booking: "إلغاء الحجز",
  login_required: "يرجى تسجيل الدخول لعرض أو حجز تفاصيل الحصة",
  class_not_found: "تعذر العثور على هذه الحصة",
  no_trainer_data: "لا توجد بيانات للمدرب",
  cancel_class: "إلغاء الحصة",
  cancel_confirmation: "هل تريد إلغاء حصتك من",
  no: "لا",
  yes: "نعم",
  class_canceled_success: "تم إلغاء الحصة بنجاح ✅",
  class_cancel_failed: "فشل في إلغاء الحصة. حاول مرة أخرى.",
  tap_to_cancel: "اضغط للإلغاء",
  working_days: "أيام العمل",
  no_booked_classes: "لا توجد حصص محجوزة",
  other_bookings: "حجوزات أخرى",
  no_other_booked_classes: "لا توجد حجوزات أخرى",
  book_this_trainer: "احجز هذا المدرب",
  book_session_with: "احجز جلسة مع",
  available_hours: "ساعات التوفر",

  notes_optional: "ملاحظات (اختياري)",
  add_notes_placeholder: "أضف ملاحظات أو أهداف للجلسة",
  confirm_booking: "تأكيد الحجز",
  missing_date: "تاريخ مفقود",
  missing_date_message: "يرجى اختيار تاريخ.",
  invalid_time: "وقت غير صالح",
  invalid_time_message: "يجب أن يكون وقت 'إلى' بعد وقت 'من'.",
  unavailable: "غير متاح",
  trainer_not_working: "المدرب لا يعمل في هذا اليوم.",
  outside_working_hours: "المدرب يعمل فقط من {from} إلى {to}",
  time_conflict: "تعارض وقت",
  time_conflict_message:
    "لا يمكنك الحجز في هذا الوقت. هناك جلسة مجدولة بالفعل.",
  error_user_not_found: "لم يتم العثور على بيانات المستخدم.",
  booking_success: "✅ تم تأكيد حجز الجلسة",
  booking_success_message: "تم حجز الجلسة بنجاح!",
  error_generic: "حدث خطأ ما",
  invalid_past_date: "تاريخ غير صالح",
  invalid_past_date_message: "لا يمكنك حجز جلسة في الماضي.",
  pt_dashboard_title: "لوحة تحكم المدرب",
  dashboard: {
    title: "لوحة المدربين",
    loading: "جاري تحميل المدربين...",
    noPTs: "لم يتم العثور على مدربين",
    noPTsSubtitle: "لا يوجد مدربون شخصيون متاحون حالياً",
    error: {
      title: "عذراً! حدث خطأ ما",
      network: "خطأ في الشبكة. يرجى التحقق من اتصال الإنترنت.",
      server: "خطأ في الخادم. تم إبلاغ فريقنا.",
      accessDenied: "تم رفض الوصول. يرجى الاتصال بالمسؤول.",
      sessionExpired: "انتهت الجلسة. يرجى تسجيل الدخول مرة أخرى.",
      general: "فشل تحميل بيانات المدربين. يرجى المحاولة مرة أخرى.",
    },
  },
  ptInfo: {
    gymId: "معرف النادي",
    ptId: "معرف المدرب",
    totalShifts: "إجمالي الورديات",
    days: "أيام",
    day: "يوم",
  },
  workSchedule: {
    title: "جدول العمل",
    addShift: "إضافة وردية",
    noSchedule: "لا يوجد جدول عمل",
    noScheduleText: "لم يتم تكوين ساعات العمل لهذا المدرب",
    addFirstShift: "إضافة أول وردية",
  },
  bookedClasses: {
    title: "حصة تدريبية المحجوزة",
    noClasses: "لا توجد فصول محجوزة",
    noClassesText: "لا يوجد لدى هذا المدرب جلسات محجوزة بعد",
  },
  modals: {
    addShift: {
      title: "إضافة وردية عمل",
      subtitle: "جدولة ساعات العمل الجديدة",
      selectDay: "اختر اليوم",
      selectDayDesc: "اختر يوم للوردية",
      timeSlot: "الفترة الزمنية",
      timeSlotDesc: "تعيين وقت البداية والنهاية",
      startTime: "وقت البدء",
      endTime: "وقت الانتهاء",
      shiftDuration: "مدة الوردية",
      hours: "ساعات",
      cancel: "إلغاء",
      confirm: "تأكيد الوردية",
    },
    editShift: {
      title: "تعديل وردية العمل",
      subtitle: "تحديث ساعات العمل • معرف الوردية:",
      editDay: "تعديل اليوم",
      editDayDesc: "تغيير اليوم لهذه الوردية",
      editTimeSlot: "تعديل الفترة الزمنية",
      editTimeSlotDesc: "تحديث وقت البداية والنهاية",
      newDuration: "المدة الجديدة",
      current: "الحالي",
      update: "تحديث الوردية",
    },
    deleteShift: {
      title: "حذف وردية العمل",
      subtitle: "لا يمكن التراجع عن هذا الإجراء",
      shiftDetails: "تفاصيل الوردية",
      day: "اليوم:",
      from: "من:",
      to: "إلى:",
      shiftId: "معرف الوردية:",
      warning:
        "سيؤدي حذف هذه الوردية إلى إزالتها نهائياً من الجدول. قد تتأثر أي فصول محجوزة لهذه الوردية.",
      cancel: "إلغاء",
      delete: "حذف الوردية",
    },
  },
  alerts: {
    logout: "تسجيل الخروج",
    logoutConfirm: "هل أنت متأكد من رغبتك في تسجيل الخروج؟",
    cancel: "إلغاء",
    success: "نجاح",
    shiftAdded: "تمت إضافة وردية العمل بنجاح!",
    shiftUpdated: "تم تحديث وردية العمل بنجاح!",
    shiftDeleted: "تم حذف وردية العمل بنجاح!",
    error: "خطأ",
    noDay: "يرجى تحديد أو إدخال يوم",
    noToken: "لا يوجد رمز مصادقة متاح. يرجى تسجيل الدخول مرة أخرى.",
    noPermission: "ليس لديك إذن لإدارة ورديات العمل.",
    shiftNotFound: "وردية العمل هذه لم تعد موجودة.",
    invalidTime: "يجب أن يكون وقت الانتهاء بعد وقت البدء.",
  },
  days: {
    monday: "الاثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    saturday: "السبت",
    sunday: "الأحد",
  },
  time: {
    am: "ص",
    pm: "م",
    na: "غير متاح",
  },

  title: "إنشاء خطة تغذية",
  ptId: "معرف المدرب",

  // User Selection
  selectUserTitle: "اختر اللاعب",
  selectUserPrompt: "يرجى تحديد مستخدم لإنشاء خطة تغذية",
  selectUserButton: "اختر اللاعب",
  changeUser: "تغيير اللاعب",
  viewPlans: "عرض الخطط",
  selectedUser: "المستخدم المحدد",
  userId: "معرف اللاعب",
  noUsersFound: "لم يتم العثور على مستخدمين",

  // Form Sections
  planNames: "أسماء الخطة",
  planNamesSub: "أدخل أسماء الخطة باللغتين",
  englishName: "الاسم بالإنجليزية *",
  arabicName: "الاسم بالعربية *",
  englishNamePlaceholder: "مثال: خطة خسارة الوزن",
  arabicNamePlaceholder: "مثال: خطة خسارة الوزن",

  descriptions: "الوصف",
  descriptionsSub: "انقر لإضافة محتوى منسق",
  englishDescription: "الوصف بالإنجليزية",
  arabicDescription: "الوصف بالعربية",
  clickToFormat: "انقر لتنسيق المحتوى",
  clickToFormatAr: "انقر لتنسيق المحتوى",

  nutritionalInfo: "المعلومات الغذائية",
  nutritionalInfoSub: "حدد الأهداف الغذائية اليومية",
  caloriesPerDay: "السعرات الحرارية يومياً *",
  protein: "البروتين *",
  carbs: "الكربوهيدرات *",
  caloriesPlaceholder: "مثال: 2000",
  proteinPlaceholder: "مثال: 150",
  carbsPlaceholder: "مثال: 250",
  kcal: "سعرة",
  grams: "غرام",

  // Format Modal
  formatModalTitleEn: "الوصف بالإنجليزية",
  formatModalTitleAr: "الوصف بالعربية",
  bodyContent: "محتوى الوصف *",
  preview: "تفاصيل الخطة:",
  toolbarHint: "حدد النص واستخدم شريط الأدوات أعلاه لتنسيق المحتوى",

  // Toolbar
  toolbarHeadings: ["ع1", "ع2", "ع3", "ع4", "ع5", "ع6"],
  toolbarSizes: ["ص", "ك", "ضخ"],
  toolbarFormatting: ["غ", "م", "ت"],
  toolbarElements: ["رابط", "نقطة", "مرقمة", "فاصل"],

  // Buttons
  resetForm: "إعادة تعيين ",
  createPlan: "إنشاء خطة تغذية",
  submitting: "جاري الإرسال...",

  // Alerts
  confirmReset: "إعادة تعيين النموذج",
  resetConfirmation: "هل أنت متأكد أنك تريد إعادة تعيين جميع الحقول؟",
  reset: "إعادة تعيين",

  // Validation Errors
  errorMemberId: "لم يتم العثور على معرف العضو",
  errorSelectUser: "يرجى تحديد مستخدم",
  errorPlanNameEn: "يرجى إدخال اسم الخطة بالإنجليزية",
  errorPlanNameAr: "يرجى إدخال اسم الخطة بالعربية",
  errorDescriptionEn: "يرجى إضافة وصف بالإنجليزية",
  errorDescriptionAr: "يرجى إضافة وصف بالعربية",
  errorCalories: "يرجى إدخال السعرات الحرارية يومياً",
  errorProtein: "يرجى إدخال غرامات البروتين",
  errorCarbs: "يرجى إدخال غرامات الكربوهيدرات",
  nutrition_details: "تفاصيل",
  // Success Messages
  successTitle: "نجاح",
  successMessage: "تم إنشاء خطة التغذية بنجاح!",
  ok: "موافق",

  // Error Messages
  errorTitle: "خطأ",
  errorNoToken: "لا يوجد رمز مصادقة متاح",
  errorNoMembershipId:
    "المستخدم المحدد ليس لديه معرف عضوية. يرجى تحديد مستخدم مختلف.",
  errorFailedToLoad: "فشل في تحميل المستخدمين",
  errorFailedToCreate: "فشل في إنشاء خطة التغذية. يرجى المحاولة مرة أخرى.",

  // Footer Note
  footerNote:
    "جميع الحقول المميزة بـ * مطلوبة. انقر على أزرار الوصف لتنسيق المحتوى.",
  welcomeBack: "أهلاً بعودتك،",
  nutritionPlans: "خطط التغذية",

  // Stats
  totalPlans: "إجمالي الخطط",
  activeClients: "العملاء النشطين",
  totalCalories: "إجمالي السعرات",

  // Card
  plan: "خطة",

  planDetails: "تفاصيل الخطة",
  noDescription: "لا يوجد وصف متاح",
  viewFullDetails: "عرض التفاصيل الكاملة",

  // Empty States
  noPlansTitle: "لا توجد خطط تغذية بعد",
  noPlansMessage: "ابدأ بإنشاء خطط التغذية لعملائك لتراها هنا",
  refreshList: "تحديث القائمة",

  // Error States
  connectionError: "خطأ في الاتصال",
  tryAgain: "حاول مرة أخرى",

  // Loading
  loadingText: "جاري تحميل خطط التغذية",
  loadingSubtext: "جاري تحضير لوحة التحكم...",

  // Alerts
  share: "مشاركة",

  remove: "إزالة",
  clear: "مسح",
  select: "اختيار",
  search: "بحث",
  refresh: "تحديث",

  warning: "تحذير",
  info: "معلومة",

  // Exercise Schedules
  exerciseSchedules: "جداول التمارين",
  manageWorkoutExercises: "إدارة تمارين التمرين",
  totalExercises: "إجمالي التمارين",
  clients: "عملاء",
  noClients: "لا يوجد عملاء",
  client: "عميل",
  pt: "مدرب شخصي",

  // Exercise Details
  exercise: "تمرين",
  muscleGroup: "مجموعة عضلية",
  rounds: "جولات",

  repsPerRound: "تكرارات لكل جولة",
  repsPerSet: "تكرارات لكل مجموعة",
  day: "يوم",
  trainingDay: "يوم التدريب",
  fromDate: "من",
  toDate: "إلى",
  schedule: "جدول",
  duration: "المدة",

  // Actions
  createSchedule: "إنشاء جدول",
  addExercise: "إضافة تمرين",
  addToScheduleDraft: "إضافة إلى مسودة الجدول",
  updateInDraft: "تحديث في المسودة",
  saveSchedule: "حفظ الجدول",
  editExercise: "تعديل التمرين",
  updateExercise: "تحديث التمرين",
  deleteExercise: "حذف التمرين",
  addToMuscleExercise: "إضافة إلى العضلات والتمارين لهذا العميل",

  // Messages
  loadingExerciseSchedules: "جاري تحميل جداول التمارين...",
  noExercisesClient: "لا توجد تمارين لهذا اللاعب",
  exerciseAddedDraft:
    "تمت إضافة التمرين إلى المسودة! أضف المزيد أو احفظ الجدول.",
  exerciseUpdatedDraft: "تم تحديث التمرين في المسودة!",
  exerciseRemovedDraft: "تمت إزالة التمرين من المسودة.",
  allDraftCleared: "تم مسح جميع عناصر المسودة.",
  editModeCancelled: "تم إلغاء وضع التعديل.",
  scheduleSaved: "تم حفظ الجدول بنجاح!",
  exerciseDeleted: "تم حذف التمرين بنجاح!",
  editingMode:
    'وضع التعديل: قم بإجراء التغييرات أدناه وانقر على "تحديث في المسودة"',

  // Validation Messages
  fillAllFields:
    "يرجى ملء جميع الحقول: العضلة، التمرين، اليوم، الجولات، والتكرارات",
  addOneExercise: "يرجى إضافة تمرين واحد على الأقل إلى الجدول",
  selectMuscleFirst: "يرجى اختيار مجموعة عضلية أولاً",
  noExercisesMuscle: "لم يتم العثور على تمارين لهذه المجموعة العضلية",
  exerciseExists: "هذا التمرين مضاف بالفعل لهذا اليوم والعضلة.",
  selectClient: "اختيار عميل",
  tapSelectClient: "انقر لاختيار عميل",
  tapSelectMuscle: "انقر لاختيار عضلة",
  tapSelectExercise: "انقر لاختيار تمرين",
  tapSelectDay: "انقر لاختيار يوم",

  // Days
  day1: "اليوم ١",
  day2: "اليوم ٢",
  day3: "اليوم ٣",
  day4: "اليوم ٤",
  day5: "اليوم ٥",
  day6: "اليوم ٦",
  day7: "اليوم ٧",
  monday: "الاثنين",
  tuesday: "الثلاثاء",
  wednesday: "الأربعاء",
  thursday: "الخميس",
  friday: "الجمعة",
  saturday: "السبت",
  sunday: "الأحد",

  // Modals
  createScheduleTitle: "إنشاء جدول",
  editExerciseTitle: "تعديل التمرين",
  currentValues: "القيم الحالية",
  changeMuscleGroup: "تغيير المجموعة العضلية",
  changeExercise: "تغيير التمرين",
  changeTrainingDay: "تغيير يوم التدريب",
  updatePreview: "معاينة التحديث",

  // Months (for date formatting)
  january: "يناير",
  february: "فبراير",
  march: "مارس",
  april: "أبريل",
  may: "مايو",
  june: "يونيو",
  july: "يوليو",
  august: "أغسطس",
  september: "سبتمبر",
  october: "أكتوبر",
  november: "نوفمبر",
  december: "ديسمبر",

  nutrition_plans: "خطط التغذية",
  nutrition_plan: "خطة التغذية",
  loading_nutrition_plans: "جارٍ تحميل خطط التغذية...",
  unable_to_load_plans: "تعذّر تحميل الخطط",
  check_connection: "يرجى التحقق من اتصالك والمحاولة مجددًا.",
  retry: "إعادة المحاولة",
  try_again: "حاول مجددًا",
  server_error: "خطأ في الخادم",
  total_plans: "إجمالي الخطط",
  no_active_plans: "لا توجد خطط نشطة",
  no_plans_message: "ليس لديك أي خطط تغذية بعد. تواصل مع مدربك للبدء.",
  view_full_description: "← عرض الوصف الكامل",
  no_description: "لا يوجد وصف متاح",
  no_detailed_description: "لا يوجد وصف تفصيلي متاح",
  kcal_per_day: "سعرة/يوم",
  g_protein: "غ بروتين",
  g_carbs: "غ كربوهيدرات",
  trainer: "المدرب",
  na: "غير محدد",
  active: "نشط",
  showing_plans: "عرض %{count} من أصل %{total} خطة",
  full_description: "الوصف الكامل",

  assigned_by_trainer: "معيّن من المدرب",

  enter_progress_name: "يرجى إدخال اسم للتقدم.",
  enter_history_value: "أدخل قيمة السجل.",
  selected: "المحدد",
  file: "ملف",
  name_ar: "الاسم بالعربي",
  name_en: "الاسم بالإنجليزي",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  confirm_password: "تأكيد كلمة المرور",
  guest: "الدخول كضيف",

  errors: {
    name_ar_required: "الاسم العربي مطلوب",
    name_en_required: "الاسم الإنجليزي مطلوب",
    phone_required: "رقم الهاتف مطلوب",
    phone_invalid: "أدخل رقم هاتف صحيح",
    email_required: "البريد الإلكتروني مطلوب",
    email_invalid: "أدخل بريد إلكتروني صحيح",
    password_required: "كلمة المرور مطلوبة",
    password_min: "على الأقل 6 أحرف",
    confirm_required: "أكد كلمة المرور",
    password_match: "كلمات المرور غير متطابقة",
    invalid_phone: "رقم الهاتف غير صالح",
    invalid_email: "البريد الإلكتروني غير صالح",
    password_length: "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",

    email_taken:
      "هذا البريد الإلكتروني مسجل بالفعل. الرجاء تسجيل الدخول أو استخدام بريد إلكتروني آخر.",
    signup_failed: "حدث خطأ ما. الرجاء المحاولة مرة أخرى.",
    registration_failed: "فشل التسجيل",
    network_error: "خطأ في الشبكة. تحقق من اتصالك وحاول مرة أخرى.",
  },
  refreshing_notes: "جاري تحديث الملاحظات...",
  no_notes: "لا توجد ملاحظات بعد",
  add_first_note: "اضغط + لإضافة أول ملاحظة",
  chat_placeholder: "اكتب رسالة...",
  chat_title: "المساعد الذكي",
  chat_welcome: "مرحباً! كيف يمكنني مساعدتك؟",
  chat_reply: "شكراً لرسالتك! سيتم الرد عليك قريباً.",
  class_finished: "تم الانتهاء من الحصة",
  noPersonalTrainersYet: "لا يوجد مدربون شخصيون حتى الآن",
  male: "ذكر",
  female: "أنثى",
  selectGender: "اختر الجنس",
  hourly_estimate_title: "تقدير اليوم",
  visits: "زيارات",
  so_far: "حتى الآن",
  actual: "فعلي",
  estimated: "تقديري",
  my_wallet: "محفظتي",
  current_balance: "الرصيد الحالي",
  points: "نقطة",
  view_history1: "السجل",
  wallet_history_title: "سجل المحفظة",
  total_transactions: "المعاملات",
  total_spent: "إجمالي الإنفاق",
  no_wallet_history: "لا توجد معاملات بعد",
  wait_5_minutes:
    "الرجاء الانتظار 1 دقائق قبل تسجيل الحضور أو الانصراف مرة أخرى",
  no_open_ticket: "لا يوجد تذكرة بيع مفتوحة لهذا النادي",
  must_check_in_first: "يجب تسجيل الحضور أولاً",
  Complaints: "شكاوي",
  complaint_title_label: "العنوان",
  complaint_title_placeholder: "ملخص موجز للشكوى",
  complaint_description_label: "الوصف",
  complaint_description_placeholder: "صف المشكلة بالتفصيل",
  complaint_add_image: "إضافة صورة",
  complaint_add_video: "إضافة فيديو",
  complaint_record_voice: "تسجيل ملاحظة صوتية",
  complaint_stop_recording: "إيقاف التسجيل",
  complaint_voice_attached: "تم إرفاق الملاحظة الصوتية",
  complaint_show_name: "إظهار اسمي لموظفي النادي",
  complaint_submit: "إرسال الشكوى",
  complaint_title: "إرسال شكوى",
  complaint_success: "تم إرسال شكواك بنجاح.",
  complaint_missing_title: "يرجى إدخال العنوان.",
  complaint_missing_description: "يرجى إدخال الوصف.",
  complaint_generic_error: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
  media_permission_required: "إذن الوصول إلى الوسائط مطلوب.",
  mic_permission_required: "إذن الميكروفون مطلوب لتسجيل ملاحظة صوتية.",
  no_Enough_balance: "لا يوجد رصيد كافي",
  ticket_purchased_success: "تم شراء التذكرة بنجاح",
  Complaints_History: "سجل الشكاوي",
  complaint_status_pending: "قيد الانتظار",
  complaint_status_resolved: "تم الحل",
  complaint_status_rejected: "مرفوضة",
  complaint_video: "فيديو",
  complaint_voice: "ملاحظة صوتية",
  no_complaints: "لا توجد شكاوى بعد",
  confirm_book_class: "هل أنت متأكد أنك تريد حجز هذا الحصة تدريبية؟",
  paid_class: "حصة تدريبية مدفوع",
  price: "السعر",
  currency: "دينار",
  wallet_withdraw_notice: "هذا حصة تدريبية مدفوع —",
  will_be_deducted_from_wallet: "سيتم خصمه من محفظتك.",
  login_required_title: "تسجيل الدخول مطلوب",
  login_required_view_class: "الرجاء تسجيل الدخول لعرض تفاصيل الحصة تدريبية.",
  login_required_book_class: "الرجاء تسجيل الدخول لحجز الحصة تدريبية.",
  class_not_found_title: "الحصة تدريبية غير موجود",
  class_not_found_message: "تعذر العثور على هذا الحصة تدريبية.",
  class_not_found_cannot_book: "الحصة تدريبية غير موجود، لا يمكن الحجز.",
  error_title: "خطأ",
  already_booked_title: "محجوز مسبقاً",
  already_booked_message: "لقد قمت بحجز هذا الحصة تدريبية مسبقاً.",
  class_full_title: "الحصة تدريبية ممتلئ",
  class_full_message: "عذراً، هذا الحصة تدريبية محجوز بالكامل.",
  booking_failed_title: "فشل الحجز",
  booking_failed_message: "تعذر حجز هذا الحصة تدريبية.",
  booking_confirmed_title: "✅ تم تأكيد الحجز",
  booking_confirmed_message: "لقد حجزت %{name} بنجاح!",
  booking_error_message: "حدث خطأ غير متوقع أثناء الحجز.",
  load_class_error: "تعذر تحميل تفاصيل الحصة تدريبية.",
  no_class_data: "لا توجد بيانات لهذا الحصة تدريبية",
  user_not_authenticated: "المستخدم غير مصرح له",
  cancel_booking_failed: "تعذر إلغاء هذا الحجز.",
  cancel_booking_success: "✅ تم إلغاء الحجز بنجاح",
  cancel_booking_error: "حدث خطأ أثناء إلغاء الحجز.",
  class_already_started:
    "لقد بدأ هذا الحصة تدريبية بالفعل ولم يعد بالإمكان حجزه.",
  insufficient_wallet_balance: "رصيد المحفظة غير كافٍ لحجز هذا الحصة تدريبية.",
  class_full_short: "ممتلئ",
  cancel_booking_title: "إلغاء الحجز",
  confirm_cancel_booking: "هل أنت متأكد أنك تريد إلغاء هذا الحجز؟",
  complaint_admin_response: "رد الإدارة",
};
